apiVersion: capabilities.3scale.net/v1beta1
kind: ActiveDoc
metadata:
  name: llama70b
  namespace: 3scale
  labels:
    app.kubernetes.io/instance: 3scale
spec:
  activeDocOpenAPIRef:
    url: 'https://raw.githubusercontent.com/redhat-ai-services/etx-serving-at-scale/refs/heads/main/manifests/llama70b-chat.json'
  name: llama70b
  productSystemName: llama70b
  published: true
  skipSwaggerValidations: true
  systemName: llama70b