---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llama-model
  namespace: vllm
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 60Gi
  storageClassName: ocs-storagecluster-cephfs
  volumeMode: Filesystem
